import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import { createPlaylist, addTracksToPlaylist } from "@/lib/spotify";

interface ExportBody {
  playlistName: string;
  playlistDescription: string;
  tracks: { uri: string; name: string; artist: string }[];
}

export async function POST(req: NextRequest) {
  const session = await getSession();

  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // verify the token has playlist write scopes before hitting Spotify
  // (tokens from before these scopes were added will be missing them)
  const grantedScopes = (session.scope ?? "").split(" ").filter(Boolean);
  const needsPlaylistScope =
    grantedScopes.length > 0 && // empty = old session, let it try
    !grantedScopes.includes("playlist-modify-public") &&
    !grantedScopes.includes("playlist-modify-private");

  if (needsPlaylistScope) {
    return NextResponse.json(
      { needsReauth: true, error: "playlist-scope-missing" },
      { status: 403 },
    );
  }

  try {
    const body: ExportBody = await req.json();
    const { playlistName, playlistDescription, tracks } = body;

    if (!tracks?.length) {
      return NextResponse.json(
        { error: "No tracks to export" },
        { status: 400 },
      );
    }

    // filter to only tracks that have a valid Spotify URI
    const validTracks = tracks.filter((t) => t.uri);

    if (validTracks.length === 0) {
      return NextResponse.json(
        { error: "None of the tracks were found on Spotify" },
        { status: 404 },
      );
    }

    // create the playlist on the user's account
    const playlist = await createPlaylist(
      session.accessToken,
      session.user.id,
      playlistName || "AI Curator Picks",
      playlistDescription || "Generated by Spotify AI Curator",
    );

    // add all tracks
    const uris = validTracks.map((t) => t.uri);
    await addTracksToPlaylist(session.accessToken, playlist.id, uris);

    return NextResponse.json({
      url: playlist.external_urls.spotify,
      name: playlistName,
      trackCount: validTracks.length,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "export failed";
    console.error("export failed:", message);
    // Spotify itself returned 403 — same root cause: missing scopes
    if (message.includes("403")) {
      return NextResponse.json(
        { needsReauth: true, error: "playlist-scope-missing" },
        { status: 403 },
      );
    }
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
