import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session";
import { createPlaylist, addTracksToPlaylist } from "@/lib/spotify";

interface ExportBody {
  playlistName: string;
  playlistDescription: string;
  tracks: { uri: string; name: string; artist: string }[];
}

export async function POST(req: NextRequest) {
  const session = await getSession();

  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body: ExportBody = await req.json();
    const { playlistName, playlistDescription, tracks } = body;

    if (!tracks?.length) {
      return NextResponse.json(
        { error: "No tracks to export" },
        { status: 400 },
      );
    }

    // filter to only tracks that have a valid Spotify track URI
    const validTracks = tracks.filter(
      (t) => typeof t.uri === "string" && t.uri.startsWith("spotify:track:"),
    );

    if (validTracks.length === 0) {
      return NextResponse.json(
        { error: "None of the tracks were found on Spotify" },
        { status: 404 },
      );
    }

    // create the playlist on the user's account
    const playlist = await createPlaylist(
      session.accessToken,
      playlistName || "AI Curator Picks",
      playlistDescription || "Generated by Spotify AI Curator",
    );

    // add all tracks — if this fails, at least return the empty playlist URL
    const uris = validTracks.map((t) => t.uri);
    try {
      await addTracksToPlaylist(session.accessToken, playlist.id, uris);
    } catch (addErr) {
      const addMsg = addErr instanceof Error ? addErr.message : "unknown";
      console.error("addTracks failed after playlist creation:", addMsg);
      // playlist exists — return it so the user isn't left with nothing
      return NextResponse.json(
        {
          url: playlist.external_urls.spotify,
          name: playlistName,
          trackCount: 0,
          warning: `Playlist created but tracks could not be added: ${addMsg}`,
        },
      );
    }

    return NextResponse.json({
      url: playlist.external_urls.spotify,
      name: playlistName,
      trackCount: validTracks.length,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "export failed";
    const isScopeError = (err as Error & { isScopeError?: boolean }).isScopeError === true;
    console.error("export failed:", message);

    if (isScopeError) {
      return NextResponse.json({ needsReauth: true });
    }

    return NextResponse.json({ error: message }, { status: 500 });
  }
}
